<?php

use Illuminate\Database\Seeder;
use App\Producto;

class ProductosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $productos = [
        	// ACCESORIOS -> 7
            ['cat_id' => 1, 'pro_nombre' => 'ACCESORIOS PARA VALLAS', 'pro_descripcion' => '<p>La valla con regla porta accesorios es una solucion funcional y ergonomica, que permite montar accesorios porta utiles, porta hojas ademas de un porta monitor de 01 o 02 articulaciones.</p><p>La valla cuenta ademas con un panel de corcho tapizado el cual permite tener a la mano sus documentos mas importantes.</p><p>Los 20 colores de melamina disponibles y los 10 tonos de tela que manejamos ponen a su disposicion 200 diferentes combinaciones.</p>', 'pro_imagen_default' => 'visso-accesorios-para-vallas.jpg'],
            ['cat_id' => 1, 'pro_nombre' => 'APOYA PIES', 'pro_descripcion' => '<p>Los apoya pies mejoran el confort del usuario y contribuyen a la ergonomía de las estaciones de trabajo.</p><p>Los dos modelos presentados con una bandeja o una barra, pueden ser adaptados para adaptarse a diferentes morfologías y asegurar una mejor posición del cuerpo.</p><p>Tanto la bandeja como la barra pueden ser posicionadas en 3 niveles distintos simplemente moviendo los lados triangulares en 20°, 30° o 40°.</p>', 'pro_imagen_default' => 'visso-accesorios-apoya-pies.jpg'],
            ['cat_id' => 1, 'pro_nombre' => 'PORTA CPUS', 'pro_descripcion' => '<p>El soporte cuenta con una pista de deslizamiento y giro para CPU vertical ofreciendo una dimensión ergonómica adicional en comparación con los soportes tradicionales.</p><p>Puede girar 360 grados alrededor de su eje y deslizarse hacia delante o hacia atrás más de 200 mm.</p><p>El CPU se mantiene en su lugar mediante 2 correas elásticas.</p>', 'pro_imagen_default' => 'visso-accesorios-porta-cpu.jpg'],
            ['cat_id' => 1, 'pro_nombre' => 'PORTA MONITORES', 'pro_descripcion' => '<p>El brazo monitor combina un diseño elegante y moderno, con fuertes características técnicas para mejorar la ergonomía en el puesto de trabajo.</p><p>Desarrollado con un mecanismo de contrapeso innovador y fiable (muelle ajustable probado a través de 30000 ciclos), es compatible con cualquier monitor, ya que con una verdadera fuerza constante, asegura un desplazamiento suave a través de todo el rango de movimiento.</p><p>La selección de un ángulo y una distancia de visión adecuada al monitor evitan la incomodidad postural y reduce la fatiga visual. El brazo cuenta con una instalación VESA rápida (compatible con 75 y 100mm) que rota fácilmente de manera vertical u horizontal. </p><p>Este porta monitor está hecho de acero, aluminio y ABS de un 37% de materiales reciclados logrando que el 99% de los materiales sean reciclables.</p>', 'pro_imagen_default' => 'visso-accesorios-porta-monitores.jpg'],
            ['cat_id' => 1, 'pro_nombre' => 'VALLAS 3 EN 1', 'pro_descripcion' => '<p>Innovador Sistema 3-en-1 de diseño limpio y funcional que permite la implementación de accesorios, lámparas y brazos de monitor.</p><p>Los accesorios Newport, se encargan de transformar el escritorio en una estación de trabajo personalizada y funcional, creando un espacio de trabajo mucho mas libre pero siempre manteniendo los útiles esenciales a tu alcance.</p>', 'pro_imagen_default' => 'visso-accesorios-valla-3-en-1.jpg'],

        	// ALMACENAMIENTO
            //  Armario
        	['cat_id' => 7, 'pro_nombre' => 'GERENCIALES', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-almacenamiento-armario-gerenciales.jpg'],
        	['cat_id' => 7, 'pro_nombre' => 'OPERATIVOS', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-almacenamiento-armario-operativos.jpg'],

        	// Cajoneras
        	['cat_id' => 8, 'pro_nombre' => 'Archivadores Verticales', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-almacenamiento-cajoneras-archivadores.jpg'],
            ['cat_id' => 8, 'pro_nombre' => 'Cajoneras Fijas', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-almacenamiento-cajoneras-cajonerasfija.jpg'],
            ['cat_id' => 8, 'pro_nombre' => 'Cajoneras Móviles', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-almacenamiento-cajoneras-movil.jpg'],
        	['cat_id' => 8, 'pro_nombre' => 'Porta files de bolsa horizontal', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'Porta files de bolsa Horizontal.jpg'],

        	// Credenza
        	['cat_id' => 9, 'pro_nombre' => 'Alaceneros', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-almacenamiento-credenzas-almaceneros.jpg'],
            ['cat_id' => 9, 'pro_nombre' => 'Credenza puerta corrediza', 'pro_descripcion' => '<p><strong>Características</strong></p>
<p>Por lo general sus dimensiones están entre 0.80 y 1.0 m de ancho.<br>18 colores de melamina disponibles.</p>', 'pro_imagen_default' => 'visso-almacenamiento-credenzas-corrediza.jpg'],
            ['cat_id' => 9, 'pro_nombre' => 'Credenza porta documentos', 'pro_descripcion' => '<p><strong>Características</strong></p><p>Por lo general sus dimensiones están entre 0.80 y 1.0 m de ancho.<br>18 colores de melamina disponibles.</p>', 'pro_imagen_default' => 'visso-almacenamiento-credenzas-documentos.jpg'],
            ['cat_id' => 9, 'pro_nombre' => 'Credenza puestas batientes y almacén central', 'pro_descripcion' => '<p><strong>Características</strong></p><p>Por lo general sus dimensiones están entre 0.80 y 1.0 m de ancho.18 colores de melamina disponibles.</p>', 'pro_imagen_default' => 'visso-almacenamiento-credenzas-batientes.jpg'],
            ['cat_id' => 9, 'pro_nombre' => 'Enchapadas de madera', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-almacenamiento-credenzas-enchapados.jpg'],
        	['cat_id' => 9, 'pro_nombre' => 'Credenza mixta', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-almacenamiento-credenzas-mixta.jpg'],


            // Escritorios
        	// Gerenciales
// <<<<<<< HEAD
//         	['cat_id' => 10, 'pro_nombre' => 'Delta', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-escritorio-gerenciales-delta.jpg'],
//             ['cat_id' => 10, 'pro_nombre' => 'Quadra Gerencial', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-escritorio-gerenciales-quadragerencial.jpg'],
//             ['cat_id' => 10, 'pro_nombre' => 'Quadra con cajonera', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-escritorio-gerenciales-quadra-con-cajonera.jpg'],
//             ['cat_id' => 10, 'pro_nombre' => 'Quadra con credenza', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-escritorio-gerenciales-quadra-con-credenza.jpg'],
//         	['cat_id' => 10, 'pro_nombre' => 'Targa', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-escritorio-gerenciales-targa.jpg'],

//         	// Operativos
//         	['cat_id' => 11, 'pro_nombre' => 'Linea Abaco', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-escritorio-operativos-linea-abaco.jpg'],
//         	['cat_id' => 11, 'pro_nombre' => 'Linea Aster', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-escritorio-operativos-linea-aster.jpg'],
//             ['cat_id' => 11, 'pro_nombre' => 'Linea Quadra', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-escritorio-operativos-linea-quadra.jpg'],

//         	// Presidenciales
//         	['cat_id' => 12, 'pro_nombre' => 'Ducon', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-escritorio-presidenciales-ducon.jpg'],
// =======
        	['cat_id' => 10, 'pro_nombre' => 'Delta', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-escritorios-gerenciales-delta.jpg'],
            ['cat_id' => 10, 'pro_nombre' => 'Quadra Gerencial', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-escritorios-gerenciales-quadracredenza1.jpg'],
            ['cat_id' => 10, 'pro_nombre' => 'Quadra con cajonera', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-escritorios-gerenciales-quadracajonera.jpg'],
            ['cat_id' => 10, 'pro_nombre' => 'Quadra con credenza', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-escritorios-gerenciales-quadracredenza.jpg'],
        	['cat_id' => 10, 'pro_nombre' => 'Targa', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-escritorios-gerenciales-targa.jpg'],

        	// Operativos
        	['cat_id' => 11, 'pro_nombre' => 'Linea Abaco', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-escritorios-operativos-abaco.jpg'],
        	['cat_id' => 11, 'pro_nombre' => 'Linea Aster', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-escritorios-operativos-aster.jpg'],
            ['cat_id' => 11, 'pro_nombre' => 'Linea Quadra', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-escritorios-operativos-quadra.jpg'],

        	// Presidenciales
        	['cat_id' => 12, 'pro_nombre' => 'Ducon', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-escritorios-presidenciales-ducon.jpg'],


            // MESA DE REUNION
            ['cat_id' => 4, 'pro_nombre' => 'ACCORDO', 'pro_imagen_default' => 'visso-messa-reunion-accord.jpg', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.'],
            ['cat_id' => 4, 'pro_nombre' => 'ACTIVA', 'pro_imagen_default' => 'visso-messa-reunion-activa.jpg', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.'],
            ['cat_id' => 4, 'pro_nombre' => 'AVANTI', 'pro_imagen_default' => 'visso-messa-reunion-avanti.jpg', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.'],
            ['cat_id' => 4, 'pro_nombre' => 'CIRCULAR', 'pro_imagen_default' => 'visso-messa-reunion-circular.jpg', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.'],
            ['cat_id' => 4, 'pro_nombre' => 'INIZIO', 'pro_imagen_default' => 'visso-messa-reunion-inizio.jpg', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.'],
            ['cat_id' => 4, 'pro_nombre' => 'OVALADAS', 'pro_imagen_default' => 'visso-messa-reunion-ovaladas.jpg', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.'],
            ['cat_id' => 4, 'pro_nombre' => 'REBATIBLES', 'pro_imagen_default' => 'visso-messa-reunion-rebatible.jpg', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.'],
            ['cat_id' => 4, 'pro_nombre' => 'IMPULSA', 'pro_imagen_default' => 'visso-messa-reunion-impulsa.jpg', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.'],


            // SILLONERA ERGONOMICA
        	// Gerenciales
        	['cat_id' => 13, 'pro_nombre' => 'Consiglieri alta', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-silloneria-consiglierialta.jpg'],
            ['cat_id' => 13, 'pro_nombre' => 'Consiglieri baja', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-silloneria-consiglieribaja.jpg'],
            ['cat_id' => 13, 'pro_nombre' => 'Guru alta', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-silloneria-gurualta.jpg'],
        	['cat_id' => 13, 'pro_nombre' => 'Guru baja', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-silloneria-gurubaja.jpg'],

        	// Operativos
        	['cat_id' => 14, 'pro_nombre' => 'Clio', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-silloneria-operativos-clio.jpg'],
            ['cat_id' => 14, 'pro_nombre' => 'Senior', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-silloneria-operativos-confort.jpg'],
            ['cat_id' => 14, 'pro_nombre' => 'Confort', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-silloneria-operativos-confort.jpg'],
            ['cat_id' => 14, 'pro_nombre' => 'Guidatta', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-silloneria-operativos-guiatta.jpg'],
        	['cat_id' => 14, 'pro_nombre' => 'Smart', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-silloneria-operativos-smart.jpg'],

        	// Visita
        	['cat_id' => 15, 'pro_nombre' => 'Butterfly', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-silloneria-visita-butterfly.jpg'],
            ['cat_id' => 15, 'pro_nombre' => 'Iso Carpeta', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-silloneria-visita-iso.jpg'],
            ['cat_id' => 15, 'pro_nombre' => 'Línea Iso', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-silloneria-visita-linea.jpg'],
            ['cat_id' => 15, 'pro_nombre' => 'Step Malla', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'mesas_inspira.jpg'],
            ['cat_id' => 15, 'pro_nombre' => 'Step Malla', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-silloneria-visita-stepmalla.jpg'],
            ['cat_id' => 15, 'pro_nombre' => 'Step Tapizada', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-silloneria-visita-steptapizada.jpg'],
            ['cat_id' => 15, 'pro_nombre' => 'Vp', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'mesas_inspira.jpg'],
            ['cat_id' => 15, 'pro_nombre' => 'Flip', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'mesas_inspira.jpg'],
            ['cat_id' => 15, 'pro_nombre' => 'Iso Con Brazo', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'mesas_inspira.jpg'],
        	['cat_id' => 15, 'pro_nombre' => 'Versa', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'mesas_inspira.jpg'],


        	// Sistemas modulares
        	['cat_id' => 6, 'pro_nombre' => 'SISTEMA DE PANELES', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-sistemas-modulares-paneles.jpg'],

        	// Escritorios BENCH
        	['cat_id' => 6, 'pro_nombre' => 'SISTEMAS BENCH', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'pro_imagen_default' => 'visso-sistemas-modulares-bench.jpg'],



            // ARESLINE - AMADEUS
            ['cat_id' => 16, 'pro_nombre' => 'Mesa Empresarial', 'pro_descripcion' => 'Una silla elegante y con acabados cuidados, también está disponible con el brazo completamente tapizado. La forma, moderna y actual, evoca claros elementos tradicionales, principalmente en la alineación del brazo con el respaldo. Amadeus es la solución perfecta para despachos importantes y salas de espera confortables.', 'pro_imagen_default' => 'aresline-amadeus-01.jpg'],
            ['cat_id' => 16, 'pro_nombre' => 'Sillas Mod. 1', 'pro_descripcion' => 'Una silla elegante y con acabados cuidados, también está disponible con el brazo completamente tapizado. La forma, moderna y actual, evoca claros elementos tradicionales, principalmente en la alineación del brazo con el respaldo. Amadeus es la solución perfecta para despachos importantes y salas de espera confortables.', 'pro_imagen_default' => 'aresline-amadeus-02.jpg'],
            ['cat_id' => 16, 'pro_nombre' => 'Sillas Mod. 2', 'pro_descripcion' => 'Una silla elegante y con acabados cuidados, también está disponible con el brazo completamente tapizado. La forma, moderna y actual, evoca claros elementos tradicionales, principalmente en la alineación del brazo con el respaldo. Amadeus es la solución perfecta para despachos importantes y salas de espera confortables.', 'pro_imagen_default' => 'aresline-amadeus-03.jpg'],
            ['cat_id' => 16, 'pro_nombre' => 'Escritorios', 'pro_descripcion' => 'Una silla elegante y con acabados cuidados, también está disponible con el brazo completamente tapizado. La forma, moderna y actual, evoca claros elementos tradicionales, principalmente en la alineación del brazo con el respaldo. Amadeus es la solución perfecta para despachos importantes y salas de espera confortables.', 'pro_imagen_default' => 'aresline-amadeus-04.jpg'],
            ['cat_id' => 16, 'pro_nombre' => 'Sillas Ergonomica', 'pro_descripcion' => 'Una silla elegante y con acabados cuidados, también está disponible con el brazo completamente tapizado. La forma, moderna y actual, evoca claros elementos tradicionales, principalmente en la alineación del brazo con el respaldo. Amadeus es la solución perfecta para despachos importantes y salas de espera confortables.', 'pro_imagen_default' => 'aresline-amadeus-05.jpg'],


            // ARESLINE - LINK-XPLUS
            ['cat_id' => 17, 'pro_nombre' => 'Mesa Empresarial', 'pro_descripcion' => 'Importante sillón con prestaciones de confort de nivel absoluto. El alcochado sigue en el respaldo, integrando en un único conjunto, del asiento al apoyacabeza, su línea única y refinada. Mecanismos de regulación de muy alta calidad, diversos tipos de brazos, materiales y acabados de alta gama, nada se deja al azar en este sillón de dirección que une prestaciones y diseño de manera óptima', 'pro_imagen_default' => 'aresline-xplus-01.jpg'],
            ['cat_id' => 17, 'pro_nombre' => 'Sillas Mod. 1', 'pro_descripcion' => 'Importante sillón con prestaciones de confort de nivel absoluto. El alcochado sigue en el respaldo, integrando en un único conjunto, del asiento al apoyacabeza, su línea única y refinada. Mecanismos de regulación de muy alta calidad, diversos tipos de brazos, materiales y acabados de alta gama, nada se deja al azar en este sillón de dirección que une prestaciones y diseño de manera óptima', 'pro_imagen_default' => 'aresline-xplus-02.jpg'],
            ['cat_id' => 17, 'pro_nombre' => 'Sillas Mod. 2', 'pro_descripcion' => 'Importante sillón con prestaciones de confort de nivel absoluto. El alcochado sigue en el respaldo, integrando en un único conjunto, del asiento al apoyacabeza, su línea única y refinada. Mecanismos de regulación de muy alta calidad, diversos tipos de brazos, materiales y acabados de alta gama, nada se deja al azar en este sillón de dirección que une prestaciones y diseño de manera óptima', 'pro_imagen_default' => 'aresline-xplus-03.jpg'],
            ['cat_id' => 17, 'pro_nombre' => 'Escritorios', 'pro_descripcion' => 'Importante sillón con prestaciones de confort de nivel absoluto. El alcochado sigue en el respaldo, integrando en un único conjunto, del asiento al apoyacabeza, su línea única y refinada. Mecanismos de regulación de muy alta calidad, diversos tipos de brazos, materiales y acabados de alta gama, nada se deja al azar en este sillón de dirección que une prestaciones y diseño de manera óptima', 'pro_imagen_default' => 'aresline-xplus-04.jpg'],


            // ARESLINE - PARLAMENT
            ['cat_id' => 18, 'pro_nombre' => 'Mesa Empresarial', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'pro_imagen_default' => 'aresline-parlament-01.jpg'],
            ['cat_id' => 18, 'pro_nombre' => 'Sillas Mod. 1', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'pro_imagen_default' => 'aresline-parlament-02.jpg'],
            ['cat_id' => 18, 'pro_nombre' => 'Sillas Mod. 2', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'pro_imagen_default' => 'aresline-parlament-03.jpg'],
            ['cat_id' => 18, 'pro_nombre' => 'Escritorios', 'pro_descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'pro_imagen_default' => 'aresline-parlament-04.jpg'],

            // ARESLINE - PF3
            ['cat_id' => 19, 'pro_nombre' => 'Mesa Empresarial', 'pro_descripcion' => '<p>La colección PF3 presenta un mobiliario completo especialmente diseñado para los salones más exclusivos, con un producto versátil, innovador y a la vez atractivo y cómodo. Una línea de descanso única que expresa una visión original del mundo de la decoración.</p>', 'pro_imagen_default' => 'aresline-pf3-01.jpg'],
            ['cat_id' => 19, 'pro_nombre' => 'Sillas Mod. 1', 'pro_descripcion' => '<p>La colección PF3 presenta un mobiliario completo especialmente diseñado para los salones más exclusivos, con un producto versátil, innovador y a la vez atractivo y cómodo. Una línea de descanso única que expresa una visión original del mundo de la decoración.</p>', 'pro_imagen_default' => 'aresline-pf3-02.jpg'],
            ['cat_id' => 19, 'pro_nombre' => 'Sillas Mod. 2', 'pro_descripcion' => '<p>La colección PF3 presenta un mobiliario completo especialmente diseñado para los salones más exclusivos, con un producto versátil, innovador y a la vez atractivo y cómodo. Una línea de descanso única que expresa una visión original del mundo de la decoración.</p>', 'pro_imagen_default' => 'aresline-pf3-03.jpg'],
            ['cat_id' => 19, 'pro_nombre' => 'Escritorios', 'pro_descripcion' => '<p>La colección PF3 presenta un mobiliario completo especialmente diseñado para los salones más exclusivos, con un producto versátil, innovador y a la vez atractivo y cómodo. Una línea de descanso única que expresa una visión original del mundo de la decoración.</p>', 'pro_imagen_default' => 'aresline-pf3-04.jpg'],
            ['cat_id' => 19, 'pro_nombre' => 'Sillas Ergonomica', 'pro_descripcion' => '<p>La colección PF3 presenta un mobiliario completo especialmente diseñado para los salones más exclusivos, con un producto versátil, innovador y a la vez atractivo y cómodo. Una línea de descanso única que expresa una visión original del mundo de la decoración.</p>', 'pro_imagen_default' => 'aresline-pf3-05.jpg'],

            // ARESLINE - TRENDY
            ['cat_id' => 20, 'pro_nombre' => 'Mesa Empresarial', 'pro_descripcion' => '<p>El diseño especial del acolchado del respaldo y la base de aluminio, bruñido o barnizado, exaltan la actualidad de Trendy First Class. Unas preciosas costuras en contraste, hechas a pedido en los tapizados de piel y ecopiel, completan el toque a la moda de esta silla.</p>', 'pro_imagen_default' => 'aresline-trendy-01.jpg'],
            ['cat_id' => 20, 'pro_nombre' => 'Sillas Mod. 1', 'pro_descripcion' => '<p>El diseño especial del acolchado del respaldo y la base de aluminio, bruñido o barnizado, exaltan la actualidad de Trendy First Class. Unas preciosas costuras en contraste, hechas a pedido en los tapizados de piel y ecopiel, completan el toque a la moda de esta silla.</p>', 'pro_imagen_default' => 'aresline-trendy-02.jpg'],
            ['cat_id' => 20, 'pro_nombre' => 'Sillas Mod. 2', 'pro_descripcion' => '<p>El diseño especial del acolchado del respaldo y la base de aluminio, bruñido o barnizado, exaltan la actualidad de Trendy First Class. Unas preciosas costuras en contraste, hechas a pedido en los tapizados de piel y ecopiel, completan el toque a la moda de esta silla.</p>', 'pro_imagen_default' => 'aresline-trendy-03.jpg'],
            ['cat_id' => 20, 'pro_nombre' => 'Escritorios', 'pro_descripcion' => '<p>El diseño especial del acolchado del respaldo y la base de aluminio, bruñido o barnizado, exaltan la actualidad de Trendy First Class. Unas preciosas costuras en contraste, hechas a pedido en los tapizados de piel y ecopiel, completan el toque a la moda de esta silla.</p>', 'pro_imagen_default' => 'aresline-trendy-04.jpg'],

            // ARESLINE - XTEN
            ['cat_id' => 21, 'pro_nombre' => 'Mesa Empresarial', 'pro_descripcion' => '<p>El estímulo fuerte y continuo propuesto por Pininfarina en términos de investigación tecnológica, soluciones de ingeniería y atención al valor estético del producto, han producido soluciones contemporáneas y avanzadas desde el punto de vista ergonómico.</p>', 'pro_imagen_default' => 'aresline-xten-01.jpg'],
            ['cat_id' => 21, 'pro_nombre' => 'Sillas Mod. 1', 'pro_descripcion' => '<p>El estímulo fuerte y continuo propuesto por Pininfarina en términos de investigación tecnológica, soluciones de ingeniería y atención al valor estético del producto, han producido soluciones contemporáneas y avanzadas desde el punto de vista ergonómico.</p>', 'pro_imagen_default' => 'aresline-xten-02.jpg'],
            ['cat_id' => 21, 'pro_nombre' => 'Sillas Mod. 2', 'pro_descripcion' => '<p>El estímulo fuerte y continuo propuesto por Pininfarina en términos de investigación tecnológica, soluciones de ingeniería y atención al valor estético del producto, han producido soluciones contemporáneas y avanzadas desde el punto de vista ergonómico.</p>', 'pro_imagen_default' => 'aresline-xten-03.jpg'],
            ['cat_id' => 21, 'pro_nombre' => 'Escritorios', 'pro_descripcion' => '<p>El estímulo fuerte y continuo propuesto por Pininfarina en términos de investigación tecnológica, soluciones de ingeniería y atención al valor estético del producto, han producido soluciones contemporáneas y avanzadas desde el punto de vista ergonómico.</p>', 'pro_imagen_default' => 'aresline-xten-04.jpg'],


            // CUADRIFOGLIO - MOBILIARIO
            ['cat_id' => 22, 'pro_nombre' => 'BOISERIE', 'pro_descripcion' => '<p>Un nuevo concepto de sistema de almacenamiento que quiere convertirse en un elemento decorativo. Espaldas de melamina, estantes de vidrio, estructuras blanco y cromado: el equilibrio perfecto de las formas geométricas . Gracias a la posibilidad de insertar melamina y puertas de vidrio, Boiserie puede ser abierto o cerrado de almacenamiento, esto depende de usted porque el resultado será siempre un éxito.</p>', 'pro_imagen_default' => 'quadri-mobiliario-boilere.jpg'],
            ['cat_id' => 22, 'pro_nombre' => 'DIRECCIONALES', 'pro_descripcion' => '<p>T45, un puente entre lo clásico y lo moderno.</p><p>Gracias a la pureza extrema de sus líneas y su fuerte personalidad, la nueva colección T45 confiere a los espacios de oficina una agradable combinación entre estilo, las nuevas tendencias estéticas y las más clásicas, la solidez formal y la funcionalidad.</p><p>Gracias a su diseño minimalista y lineal, T45 se distingue por su unión a 45° entre tablero y estructura y las combinaciones de acabados melamínicos.</p>', 'pro_imagen_default' => 'quadri-mobiliario-direccionales.jpg'],
            ['cat_id' => 22, 'pro_nombre' => 'MOSTRADORES', 'pro_descripcion' => '<ul><li>Módulos rectos realizados en tablero aglomerado de partículas de espesor 25mm, revestidos con papel melamínico.</li><li>Lavable, antirreflejos, anti-arañazos</li><li>Acabados blanco, nogal, canaletto y wengué a por semi-abierto con cantos en ABS anti-golpes</li><li>Patas realizadas en tubo de acero trefilado decapado con sección cuadrada</li><li>Sistema de iluminación</li></ul>', 'pro_imagen_default' => 'quadri-mobiliario-mostradores.jpg'],
            ['cat_id' => 22, 'pro_nombre' => 'OPERATIVOS', 'pro_descripcion' => '<ul><li>Sobres realizados en tablero aglomerado de partículas de esp. 30mm. Revestido con papel melmaú anti-arañazos</li><li>Tapones embellecedores en ABS cromado. Tapa abatible se puede abrir en ambos sentidos y está dotada de un cepillo para cables.</li><li>Sobres en bilaminado de aglomerado de alta tensión, revestidos con melanina de alta calidad con poro abierto</li><li>Sobres en cristal extra-blanco templado anti-huella están satinados en la parte superior, barnizados con efecto opaco en la parte inferior</li><li>Placas de acero inoxidable. Cantos pulidos y esquina biselados a 45°.</li><li>Patas disponibles en las versiones ‘’abierta’’ y ‘’cerrada’’, fabricadas en perfilado de acero. Incluye pies niveladores</li></ul>', 'pro_imagen_default' => 'quadri-mobiliario-operativos.jpg'],
            ['cat_id' => 22, 'pro_nombre' => 'REUNION', 'pro_descripcion' => '<ul><li>Sobres en bilaminado de aglomerado de alta tensión, revestidos con melanina de alta calidad con poro abierto</li><li>Lavable, antirreflejos, anti-arañazos</li><li>Sobres en cristal extra-blanco templado anti-huella están satinados en la parte superior, barnizados con efecto opaco en la parte inferior</li><li>Placas de acero inoxidable. Cantos pulidos y esquina biselados a 45°.</li><li>Tapa abatible puede abrirse en ambos sentidos y está dotada de un cepillo para los cables</li></ul>', 'pro_imagen_default' => 'quadri-mobiliario-reunion.jpg'],


            // QUADRIFOGLIO - SILLAS
            ['cat_id' => 23, 'pro_nombre' => 'DIRECCIONALES', 'pro_descripcion' => '<ul><li>Sillón direccional</li><li>Brazos en polipropileno negro, acero cromado revestido y multicapa de haya barnizado natural y pintado color nogal</li><li>Respaldo alto y bajo</li><li>Versiones fijas y oscilantes</li></ul>', 'pro_imagen_default' => 'quadri-sillas-direccionales.jpg'],
            ['cat_id' => 23, 'pro_nombre' => 'OPERATIVOS', 'pro_descripcion' => '<ul><li>Sillón operativo</li><li>Respaldo con y sin reposacabeza, alto y bajo.</li><li>Versión con respaldo alto de red blanca, gris y negra</li><li>Versión con movimiento syncron</li><li>Regulación altura respaldo up/down</li></ul>', 'pro_imagen_default' => 'quadri-sillas-operativos.jpg'],
            ['cat_id' => 23, 'pro_nombre' => 'REUNIÓN', 'pro_descripcion' => '<p>Gama de silleria transversal que, gracias a un diseño que se deshace de todo lo superfluo, destaca la pureza de la silla y su forma sinuosa y envolvente. Carcasa en polipropileno en 6 acabados, resistente y flexible, ofrece no solo un excelente confort, si no también, armonía y soluciones que encajan perfectamente en todo tipo de espacios.</p>', 'pro_imagen_default' => 'quadri-sillas-reunion.jpg'],
            ['cat_id' => 23, 'pro_nombre' => 'SILLONES DE ESPERA', 'pro_descripcion' => '<ul><li>Sillón de espera</li><li>Estructura de poliuretano espumado en frío de molde</li></ul>', 'pro_imagen_default' => 'quadri-sillas-sillones-espera.jpg'],
        ];

        foreach ($productos as $key => $value) {
        	Producto::create($value);
        }
    }
}
